#!/usr/bin/env bash
# Script configures nginx to include a custome header X-Served-By with hostname of server

#Install nginx if not installed
apt-get update -y
apt-get install -y nginx

# Get the current server hostname
HOSTNAME=$(hostname)

# Add the custome header inside the default nginx configuration file
# Also remove any existing headerline with add_server X-Server-By to avoid duplicates
sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default

#Insert header inside the main server block after the listen directive
sed -i "/listen \[::\]:80 default_server;/a \    add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

#Restart nginx to apply changes
service restart nginx

